[package]
name = "oab-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
getrandom.workspace = true
ksni.workspace = true
nix.workspace = true
oab-domain = { path = "../domain", version = "=0.2.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
futures-util.workspace = true
tokio.workspace = true
zbus.workspace = true
