[package]
name = "oab-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
futures-util.workspace = true
httpdate.workspace = true
oab-domain = { path = "../domain", version = "=0.1.0" }
reqwest.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true
zeroize.workspace = true

[dev-dependencies]
oab-test-support = { path = "../test-support", version = "=0.1.0" }
serde_json.workspace = true

[lints]
workspace = true
